---
train:

    params:
        batch_size: 128
        epoch: 60
        lr: 0.0005
        decay: 0.1
        decay_step: 20
        warmup: 5
        sequence_length: 2 
        stride: 1           

    save:
        metapath: "/userhome/share_hosts/work"
        folder: diap
        model_name: dgagaze
        step: 10

    data:
        image: "/userdata/Diap.zip/EyeDiap/Image"
        label: "/userdata/Diap.zip/EyeDiap/ClusterLabel"
        pose_label: /path/to/pose_pseudo_labels.csv
        header: True
        name: diap
        isFolder: True
      

    pretrain:
        enable: True
        path: "/userhome/share_hosts/work/eth//GazeTR-H-ETH.pt"
        device: 0
        

    device: 0

    reader: reader


